### ISSUE TITLE
Project name of "deepkit" changes nested directory behavior

### ISSUE THREAD

**Issue by planetceres** [deepkit/deepkit#12]
A logical name to keep DeepKit configuration files within a project would be nested in a subdirectory called `deepkit`. However, using this convention on a DeepKit server causes inconsistency with `deepkit.yml` config values.

**Server Example**

For example, say we're training a model in a parent repo of https://github.com/username/MyNetwork.git

If we create a directory ./deepkit and put  deepkit.yml there, DeepKit can't seem to find the configuration. Notice the [object Object] placeholder value.

```
./MyNetwork
└──  deepkit
    └── deepkit.yml
```

![deepkit_issue_001](https://user-images.githubusercontent.com/7258207/80156033-c8854100-8577-11ea-9347-efc5a21c7f49.png)

But if we duplicate the same `deepkit.yml` file and nest it under `./deepkit/train`, DeepKit is able to find the config

```
./MyNetwork
└──  deepkit
    └── train
        └── deepkit.yml
```

![deepkit_issue_002](https://user-images.githubusercontent.com/7258207/80156188-274aba80-8578-11ea-8805-a4bab9aeecb4.png)

**GUI Example**

This also happens when using the GUI on localhost to manage a *Project* - but it is affected one level higher in the directory structure (so  that the `[object Object]` placeholder value appears if `./deepkit.yml` is in the root of the project:

```
./MyNetwork
└──  deepkit.yml
```

**Summary**

One solution is to make sure that DeepKit configuration files are not organized under a directory named `deepkit` . However, unless the directory name `deepkit` needs to be reserved, it might cause less confusion to correct this behavior so that experiments are not affected by this.

**Comment by marcj** [comment]
@planetceres thanks for the detailed description. Could you also please post your deepkit.yml content?  I wonder if `training` is an actual config value defined in the file, what content it has, and if `training` is correctly displayed when the bug is not seen.

**Comment by planetceres** [comment]
While the example I showed above is a private project, this same behavior happens with the default examples in this repo and the deepkit python-sdk. The only difference is that I've had to replace `parameters` with `config`.


`distributed-simple/deepkit.yml`
```
image: python:3.7.0-alpine3.8

docker:
    binds:
        - /home/user/deepkit/deepkit-python-sdk/:/deepkit-sdk
    env:
        - PYTHONPATH=/deepkit-sdk

config:
    lr: 50
    optimizer: sgd
    training:
        epochs: 50
        samples: 20

tasks:
    ...

```
