### ISSUE TITLE
Automatic provisioning of VM instances

### ISSUE THREAD

**Issue by mullerrwd** [deepkit/deepkit#19]
Checking the [configuration (deepkit.yml) documentation](https://deepkit.ai/documentation/configuration) I do not see an appropriate method to provision VM instances (E.g: MS Azure)  as a node through a REST API.

A current solution is to:
1. Start a DL VM instance and provision the instance through deepkit as node. 
2. Start an experiment.
3. When the experiment had ended or shut down per user request stop the instance.

However this does not prevent unnecessary idle time of the instance which will add up to the costs if one does not stop the instance directly after an experiment.

Preferred functionality would be:
1. Define a target VM instance within `deepkit.yml` experiment file through API.
2. Let deepkit start the instance, provision it automatically when the experiment has been started by the user.
3. When the experiment has ended stop the the instance.

Example config file:
```yaml
vm: <API: start the instance>
image: tensorflow/tensorflow:1.15.2-gpu-py3
command: python model.py
vm_post: <API: stop the instance>
```

If you have a different work around in place I would be happy to hear about it!
